# Generated by Django 3.2.9 on 2021-11-02 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommonFunction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.CharField(max_length=300)),
                ('class_name', models.CharField(max_length=300)),
                ('name', models.CharField(max_length=300)),
                ('parameters', models.TextField(blank=True, null=True)),
                ('usage', models.TextField(blank=True, null=True)),
                ('return_value', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
